# Generated by Django 3.2.11 on 2022-05-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('assset', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CheckAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Account_ID', models.CharField(max_length=50, null=True)),
                ('balance', models.FloatField(default=0)),
                ('open_date', models.DateField()),
                ('overdraft', models.FloatField(default=0)),
                ('fk_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank')),
            ],
            options={
                'unique_together': {('Account_ID', 'fk_bank')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID_card', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('c_name', models.CharField(max_length=100)),
                ('c_phone', models.CharField(max_length=11)),
                ('c_email', models.CharField(max_length=100)),
                ('c_relation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Depart_ID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('dtype', models.CharField(max_length=20)),
                ('fk_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankManage.bank')),
            ],
            options={
                'unique_together': {('Depart_ID', 'fk_bank')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID_card', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('entry_date', models.DateField()),
                ('fk_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank')),
                ('fk_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.department')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Loan_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('money', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Account_ID', models.CharField(max_length=50, null=True)),
                ('balance', models.FloatField(default=0)),
                ('open_date', models.DateField()),
                ('rate', models.FloatField()),
                ('currency_type', models.CharField(max_length=20)),
                ('fk_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank')),
            ],
            options={
                'unique_together': {('Account_ID', 'fk_bank')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('pay_money', models.FloatField()),
                ('fk_loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stype', models.CharField(max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.client')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.employee')),
            ],
            options={
                'unique_together': {('client', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='OpenStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_access', models.DateField(auto_now=True)),
                ('fk_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.storeaccount')),
                ('fk_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank')),
                ('fk_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BankManage.client')),
            ],
            options={
                'unique_together': {('fk_bank', 'fk_client')},
            },
        ),
        migrations.CreateModel(
            name='OpenCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_access', models.DateField(auto_now=True)),
                ('fk_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.checkaccount')),
                ('fk_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank')),
                ('fk_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BankManage.client')),
            ],
            options={
                'unique_together': {('fk_bank', 'fk_client')},
            },
        ),
        migrations.CreateModel(
            name='ClientLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BankManage.client')),
                ('fk_loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.loan')),
            ],
            options={
                'unique_together': {('fk_loan', 'fk_client')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Account_ID', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=0)),
                ('open_date', models.DateField()),
                ('fk_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank')),
            ],
            options={
                'unique_together': {('Account_ID', 'fk_bank')},
            },
        ),
    ]
