# Generated by Django 3.2.11 on 2022-05-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fk_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankManage.bank'),
        ),
    ]
