# Generated by Django 3.2.11 on 2022-05-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankManage', '0002_loan_fk_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
