# Generated by Django 3.2.11 on 2022-05-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankManage', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opencheck',
            name='fk_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BankManage.checkaccount'),
        ),
        migrations.AlterField(
            model_name='openstore',
            name='fk_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BankManage.storeaccount'),
        ),
    ]
